# 第一部分：网页的名称、信息
site_name: ZJU-OS25Fall-Stu
site_url: https://SuDIS-ZJU.github.io/OS25Fall/
site_author: yourname
site_description: yoursite

# 第二部分：网页的导航（所有名称均可替换）
# 这里将决定你最终展示出的文件的结构，冒号后面对应的链接应为以docs为根目录下的相对路径
nav:
- main:
  - home: index.md

# 第三部分：网页的设计（除却颜色以外建议不要修改）
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # 代码块操作
    - content.code.copy
    - content.code.select
    - content.code.annotate
    # 底部导航
    - navigation.footer
    # 顶部导航
    #- navigation.tabs
    # 侧边栏按 section 展开
    - navigation.sections
    - navigation.expand
    # 章节首页 index.md
    - navigation.indexes
    # 锚点
    - navigation.tracking
    # 路径
    - navigation.path
    # 回到顶部
    - navigation.top
    - toc.follow
    # 页面编辑
    - content.action.edit
    # 搜索
    - search.suggest
    - search.highlight
    - search.share


# 第四部分：markdown扩展语法（可以补充更多的扩展）
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde